### ISSUE TITLE
Ux Research(User Experience)

### ISSUE THREAD

**Issue by iyanuloluwa-Miracle** [zuri-training/Qr-gen-proj-team57#12]
brainstorming and the rest

**Comment by iyanuloluwa-Miracle** [comment]
Lola, Katherine,prince,modupe,Frances  contributed to it

**Comment by koiexperience** [comment]
User research

**Comment by Makie001** [comment]
User research

**Comment by iyanuloluwa-Miracle** [comment]
The following was conducted;  A comprehensive docs showing research objectives qr generator ,Live interview, Organizing notes, Pain points, User flow, User story , Idea prioritization,

**Comment by iyanuloluwa-Miracle** [comment]
All cleared!!!
