### ISSUE TITLE
Check task list to confirm allocation and task completion

### ISSUE THREAD

**Issue by Lolayemi** [zuri-training/Qr-gen-proj-team57#15]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-03209833-7fff-244d-a094-530ea6d00af2"><div dir="ltr" style="margin-left:0pt;" align="right">

Mobile Grid System and Spacers | Damilola
-- | --
Creation Profile Page Low Fidelity | Patricia
Low Fidelity Mobile view for registration page | Damilola
Low Fidelity Mobile view Sign in page | Omorinsola
Low Fidelity Mobile view for Landing page | Dina Iyanuoluwa
Low Fidelity Mobile view for FAQ page | Prince
Low Fidelity Mobile view for Dashboard | Katherine
Low Fidelity Mobile view for Verification | Prince
3 more testimonial stories to be added to the Landing Page | Ifeoluwa and Modupe
Alignment of Forgot Password Page, verify email page and Email sent page to Registration and Sign in page style | Suideen
Low Fidelity Mobile view for forgot Password, Verify Email and Email sent pages | Suideen
Style Guidefor Colour code, Input field for Desktop and Mobile for Low Fidelity and High Fidelity and Buttons adjustment to Colour code | Omolola
Low Fidelity Dashboard page for Desktop view | Omolola
Low Fidelity Scroll function for review section on Landing page for Desktop | Omolola
High Fidelity Design for the Landing Page section | Wahab and Katherine
High Fidelity Design for Sign in Page | Wahab
Creation of Low Fidelity Onboarding Pages for Desktop view | Frances
Scroll Function for Home Section Landing Page | Suideen
All Registration And Login pages (Email sent, verify email and forgot password)  High Fidelity Desktop pages | Modupe and Damilola
All Registration And Login pages (Email sent, verify email and forgot password)  High Fidelity mobile pages | Modupe and Damilola
Dashboard desktop page High Fidelity and Qr Generation Page 1,2,3 and 4 | Inioluwa
Dashboard mobile view Low Fidelity and Qr Ge | Prince
Profile page, profile History and Profile folders page both low and high fidelity  for Desktop and Mobile | Frances and Rinsola and Patricia
FaQ and how can we help page High fidelity to desktop and mobile | Abbie
Landing Page High Fidelity mobile | Ifeoluwa and Suideen
Page Uniformity and Consistency with style guide for final design roll out | Katherine, Omolola, Prince, Suideen and
Dashboard mobile view High Fidelity and Qr Generation Page 1,2,3 and 4/ convert to mobile | Dina Iyanu
Inserting of images and graphics on all pages along side prototyping functions on all pages | Wahab and Suideen
Creation of Thank you response page to How can we | Prince
Adjusting and creating responsive buttons on Style Guide | Katherine and Modupe

</div><br /></b>
</body>
</html>

**Comment by Abbie3818** [comment]
FaQ and Contact Us page Hi-Fi ( desktop and mobile)

**Comment by iyanuloluwa-Miracle** [comment]
1.Dashboard mobile view High Fidelity and Qr Generation Page 1,2,3 and 4/ convert to mobile
2. Low Fidelity Mobile view for Landing page

**Comment by Damilola10** [comment]
Contact Us page Low-Fi and Hi-Fi (Desktop)

**Comment by Frances001** [comment]
1. Creation of Low fidelity and High fidelity Onboarding pages for Desktop view
2. Creation of Profile Page, History Page, Folders Page and Settings Pages for both Low fidelity and High fidelity for Mobile view and Desktop view

**Comment by Frances001** [comment]
1. Creation of Low fidelity and High fidelity Onboarding pages for Desktop view - Frances
2. Creation of Profile Page, History Page, Folders Page and Settings Pages for both Low fidelity and High fidelity for Mobile view and Desktop view- Frances, Patricia and Rinsola

**Comment by oladimejiibrahim** [comment]
1. Inserting of images and graphics on all pages along side prototyping functions on all pages.
2. High Fidelity Design for Sign in Page

**Comment by Deity-p** [comment]
Dashboard desktop view hifi

**Comment by koiexperience** [comment]
1.All registration and login pages for mobile view
2.All registration and login pages for web view
3.Adjusting and creating responsive buttons on style guide

**Comment by Makie001** [comment]
1. Creation Profile Page Low Fidelity
2. Creation of Profile Page, History Page, Folders Page and Settings Pages for both Low fidelity and High fidelity for Mobile view and Desktop view- Frances, Patricia and Rinsola

**Comment by Aasuiudeen** [comment]
Page Uniformity and Consistency with style guide for final design roll out

**Comment by Lolayemi** [comment]
> 

Confirmed

**Comment by Lolayemi** [comment]
> Page Uniformity and Consistency with style guide for final design roll out

You know you've done more than this @Aasuiudeen

**Comment by omorinsola05** [comment]
Low fidelity for FAQ page (web view)
Low&High fidelity for Profile history page for both mobile and desktop view

**Comment by Lolayemi** [comment]
> Dashboard desktop view hifi

You have done more than this too

**Comment by Lolayemi** [comment]
> Low fidelity for FAQ page (web view) Low&High fidelity for Profile history page for both mobile and desktop view

Noted, will be corrected

**Comment by Aasuiudeen** [comment]
Inserting of images and graphics on all pages along side prototyping functions on all pages.

Page Uniformity and Consistency with style guide for final design roll out.

Landing Page High Fidelity mobile

Scroll Function for Home Section Landing Page

Hifi Desktop prototype 

Low Fidelity Mobile view for forgot Password, Verify Email and Email sent pages

**Comment by Deity-p** [comment]
Settings page both mobile and desktop view

**Comment by Deity-p** [comment]
Desktop view for dashboard hifi

**Comment by Lolayemi** [comment]
All has been sorted and completed.
